### ISSUE TITLE
Make allowed_for required or hanld it's missing in the code

### ISSUE THREAD

**Issue by cinek810** [cinek810/ansible-deployer#47]
```
(ansible)$ ansible-deployer run --task task_exec_bin_true -i plcyf -s testing 
Successfully created workdir: %s /var/ansible-deployer/20220315/SEQ0000
Traceback (most recent call last):
  File "/usr/local/ansible/bin/ansible-deployer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/ansible/lib64/python3.6/site-packages/ansible_deployer/command_line.py", line 546, in main
    if not verify_task_permissions(selected_items, user_groups):
  File "/usr/local/ansible/lib64/python3.6/site-packages/ansible_deployer/command_line.py", line 435, in verify_task_permissions
    for allow_group in s_task["allowed_for"]:
KeyError: 'allowed_for'
```

**Comment by LegenJCdary** [comment]
Please check tasks config/schema, it looks fine on my end. "allowed_for" is mandatory element for some time already, it should throw an error in load_configuration_file() not in much later verify_task_permissions().

`tasks:
  - name: testtt
    play_items:
      - run_bin_true
    allow_limit: True
`

`fazi@plcyf-fazi ansible-deployer (fixing_issues *) $ python /home/fazi/deploy-ans/ansible-deployer/ansible_deployer/command_line.py run --task testtt -i testInfra -s testing -d

2022-03-23 06:00:58,644 [DEBUG]: Successfully created workdir: /tmp/20220323/SEQ0010


2022-03-23 06:00:58,645 [DEBUG]: validate_options running for subcommand: run


2022-03-23 06:00:58,645 [DEBUG]: load_configuration called


2022-03-23 06:00:58,645 [DEBUG]: Loading :infra.yaml


2022-03-23 06:00:58,657 [DEBUG]: Loaded:
{'infrastructures': [{'name': 'testInfra', 'stages': [{'name': 'testing', 'inventory': './test_infra1_inv.yaml'}, {'name': 'prod', 'inventory': './prod_infra1_inv.yaml'}, {'name': 'locked', 'inventory': './lock_infra1_inv.yaml'}]}, {'name': 'testInfra2', 'stages': [{'name': 'testing', 'inventory': './test_infra2_inv.yaml'}]}, {'name': 'testInfra3', 'stages': [{'name': 'prod', 'inventory': './prod_infra3_inv.yaml'}]}]}


2022-03-23 06:00:58,657 [DEBUG]: Loading :tasks.yaml


2022-03-23 06:00:58,707 [CRITICAL]: {'tasks': [{0: [{'allowed_for': ['required field']}]}]}
`

**Comment by LegenJCdary** [comment]
Present since #17
