### ISSUE TITLE
Handle undefined tags

### ISSUE THREAD

**Issue by cinek810** [cinek810/ansible-deployer#52]
```
2022-03-15 12:50:19,126 [INFO]: Infra locked.

Traceback (most recent call last):
  File "/usr/local/ansible/bin/ansible-deployer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/ansible/lib64/python3.6/site-packages/ansible_deployer/command_line.py", line 551, in main
    run_task(config, options, inv_file)
  File "/usr/local/ansible/lib64/python3.6/site-packages/ansible_deployer/command_line.py", line 389, in run_task
    tags = get_tags_for_task(config, options)
  File "/usr/local/ansible/lib64/python3.6/site-packages/ansible_deployer/command_line.py", line 506, in get_tags_for_task
    tags = task["tags"]
KeyError: 'tags'
```

**Comment by LegenJCdary** [comment]
This is fixed in #50
